# setup
setup: selflabel
dataset_name: Haptics
num_classes: 5

# ema
use_ema: False

# Threshold
confidence_threshold: 0.9

# Criterion
criterion: confidence-cross-entropy
criterion_kwargs:
   apply_class_balancing: True

# Model
num_heads: 1 #1

# Dataset

num_neighbors: 5
feat_len: 160

# Transformations
augmentation_strategy: ours 

# Hyperparameters
epochs: 150 #200
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
batch_size: 1000
num_workers: 2

# Scheduler
scheduler: constant
